/* Generated by tools/build-site.mjs - do not edit. Public values only. */
window.DANANEER_CONFIG = {
  "supabaseUrl": "https://qijxhimdwiwrrqyoxsew.supabase.co",
  "supabaseAnonKey": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpanhoaW1kd2l3cnJxeW94c2V3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODkzNjQzODIsImV4cCI6MjEwNDk0MDM4Mn0.UVOCqBrQ6_wB9czq0tZ2TW5X1q-Mohe4qQcaV7DIvlQ"
};
